name = "FlagSOS"
uuid = "78b365f2-6d95-4275-8db6-8dceb35a712b"
authors = ["Daniel Brosch <73886037+DanielBrosch@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
